oauth2.client.kakao.client-id=211d3999df152d231bdd830e46ce03e7
oauth2.client.kakao.redirect-uri=http://localhost:8080/api/auth/login/code/kakao
oauth2.client.kakao.scope=profile_nickname,profile_image,talk_calendar
oauth2.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
oauth2.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
oauth2.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
oauth2.provider.kakao.calendar-uri=https://kapi.kakao.com/v2/api/calendar/events